[bot]
    debug-mode = false
    owners = []

[log]
    retention = 30 # days of logs to keep
    format = "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <level>{message}</level>"

[database]
    path = "storage/database.db"
